### ISSUE TITLE
add MQTT support

### ISSUE THREAD

**Issue by jockele79** [pdcemulator/pyHPSU-docker#1]
Hi @pdcemulator ,

is it possible to include the mqtt-functionality to the amd64 docker?
Unfortunately I'm a layman concerning docker so I,m not able to integrate this by myself,

best regards from a HPSU-user

**Comment by pdcemulator** [comment]
All output modules are available in docker. You have to configure /etc/pyHPSU/pyhpsu.conf as described in https://github.com/Spanni26/pyHPSU#output-options--o-output
MQTT is not described in README, but its similar to the other modules. I have a unmerged PR to improve the README. Use this in your config file:
```
[MQTT]
BROKER = your_broker_ip
PORT = 1883
USERNAME = 
PASSWORD = 
CLIENTNAME = rotex_hpsu
PREFIX = rotex
```

You should map this volume into a seperate mount, to persistent your modifications in case you recreate or update the container image.

**Comment by jockele79** [comment]
ok, thanks a lot. I added the mqtt part to the pyHPSU.conf but , unfortunately I get an error message when calling "pyHPSU.py -c t_dhw -c flow_rate -c water_pressure  -o MQTT  -d ELM327 -p /var/husky/devices/FTDI_FT232R_USB_UART_A52VL4UF"

Output:
"Traceback (most recent call last):
  File "/usr/bin/pyHPSU.py", line 335, in <module>
    main(sys.argv[1:])
  File "/usr/bin/pyHPSU.py", line 275, in main
    read_can(driver, logger, port, cmd, lg_code,verbose,output_type)
  File "/usr/bin/pyHPSU.py", line 330, in read_can
    module = importlib.import_module("HPSU.plugins." + module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/HPSU/plugins/mqtt.py", line 18, in <module>
    import paho.mqtt.publish as publish
ImportError: No module named 'paho'"

I tried to install the paho.mqtt but his didn't work :-(

**Comment by pdcemulator** [comment]
The Python library (paho) was not packaged into this container. I have added it now. Please download the image and test again.

**Comment by jockele79** [comment]
ok, I tested now for several days, there are still a few issues:

1) from time to time the container stops with exit code 1 or exit code 9
2) I could not manage to send a topic to mqtt, I have a running MQTT broker (Mosquitto integrated to Edomi-Docker), connection with openhab and MQTT.fix is running, but I cannot find any messages from pyhpsu. Seems like the MQTT-module is not running correctly, reading parameters for openhab and to console is working. 

Find here an extract of docker-log:

`,warning - sending cmd 31 00 FA 01 DA 00 00 (rc:>OK)
,warning - retry 1 command flow_rate
,+ '[' '!' -f /etc/pyHPSU/pyhpsu.conf ']'
,+ pyHPSU.py -a
,/usr/bin/pyHPSU.py:161: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
,  config.readfp(f)
,warning - Error setting ID 190 (rc:OK>OK)
,Traceback (most recent call last):
,  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 501, in read
,    'device reports readiness to read but returned no data '
,serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
,
,During handling of the above exception, another exception occurred:
,
,Traceback (most recent call last):
,  File "/usr/bin/pyHPSU.py", line 335, in <module>
,    main(sys.argv[1:])
,  File "/usr/bin/pyHPSU.py", line 253, in main
,    n_hpsu = HPSU(driver=driver, logger=logger, port=port, cmd=collected_cmds, lg_code=lg_code)
,  File "/usr/lib/python3/dist-packages/HPSU/HPSU.py", line 88, in __init__
,    self.initInterface(port)
,  File "/usr/lib/python3/dist-packages/HPSU/HPSU.py", line 148, in initInterface
,    self.can.initInterface(portstr=portstr, baudrate=baudrate,init=True)
,  File "/usr/lib/python3/dist-packages/HPSU/canelm327.py", line 37, in initInterface
,    rc = self.sendCommand("ATE0")
,  File "/usr/lib/python3/dist-packages/HPSU/canelm327.py", line 101, in sendCommand
,    ser_read = self.ser.read(size=100)
,  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 509, in read
,    raise SerialException('read failed: {}'.format(e))
,serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
,warning - retry 1 command t_dhw
,Exception in thread Thread-1:
,Traceback (most recent call last):
,  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
,    self.run()
,  File "/usr/lib/python3.7/threading.py", line 865, in run
,    self._target(*self._args, **self._kwargs)
,  File "/usr/bin/pyHPSU.py", line 299, in read_can
,    rc = n_hpsu.sendCommand(c, setValue)
,  File "/usr/lib/python3/dist-packages/HPSU/HPSU.py", line 154, in sendCommand
,    rc = self.can.sendCommandWithID(cmd=cmd, setValue=setValue, priority=priority)
,  File "/usr/lib/python3/dist-packages/HPSU/canelm327.py", line 110, in sendCommandWithID
,    rc = self.sendCommand("ATSH"+cmd["id"])
,  File "/usr/lib/python3/dist-packages/HPSU/canelm327.py", line 101, in sendCommand
,    ser_read = self.ser.read(size=100)
,  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 493, in read
,    buf = os.read(self.fd, size - len(read))
,TypeError: an integer is required (got type NoneType)
,
,warning - sending cmd 31 00 FA 01 DA 00 00 (rc:>OK)
,warning - retry 1 command flow_rate
,+ '[' '!' -f /etc/pyHPSU/pyhpsu.conf ']'
,+ pyHPSU.py -a
,/usr/bin/pyHPSU.py:161: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
,  config.readfp(f)`

**Comment by pdcemulator** [comment]
MQTT is working for me on a Raspi ~~inside~~ currently without docker Container.
I am using a PyCAN Board, which is not using the serial access as you do.
It seems that there is a issue with communication over serial port. How did you map this port into container? Is it working without docker (direct on your system)?

**Comment by pdcemulator** [comment]
@jockele79 what are your testing results?
"Is it working without docker (direct on your system)?"

**Comment by jockele79** [comment]
Sorry that I did not answer for a long time, I was just fighting with openhab for a lot of evenings.

As docker base I use my timberwolf server, unfortunately I cannot run pyHPSU directly there because root access is blocked (in my case as a layman a good thing :-) ). The docker is created with portainer, port 1883 is mapped in a normal way. 
At the moment I managed to bring some data to openhab and from there by MQTT to Edomi, but it's not running reliable and difficult to manage for me.

Therefore I'm thinking about buying a raspi with pycan. Can you recommend this configuration, is it running without problems?

Thanks a lot for your help

**Comment by pdcemulator** [comment]
solved with https://github.com/Spanni26/pyHPSU/issues/29
